### ISSUE TITLE
conflict between seaborn==0.11 and recent fgclustering pulls in deprecated sklearn package

### ISSUE THREAD

**Issue by rwirth** [HelmholtzAI-Consultants-Munich/XAI-Tutorials#7]
running `pip install -r requirements.txt` in a fresh Python 3.10 venv shows a message that the sklearn package is deprecated and aborts. It seems that the requirement `seaborn==0.11.2` forces fgclustering to version 0.3 because the newer versions require `seaborn >= 0.12`. The old version, in turn, depends on the deprecated package. Switching the line in `requirements.txt` to `seaborn>=0.12` installs seaborn 0.13 and fgclustering 1.0.3, which pulls in the new package scikit-learn. I haven't checked if that seaborn upgrade breaks anything.

**Comment by donatella-cea** [comment]
Thank you for the message. We removed the restriction on the seaborn version and this solves the issue.
